---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.10.3
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci

  stage-binaries:
    image: rancher/dapper:1.11.2
    commands:
    - cp -r ./bin/* ./package/
    when:
      branch: [master, release/*]
      event: [push,tag]

  docker-publish-20:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: rancher/cli
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    build_args:
    - VERSION=${DRONE_TAG}
    when:
      branch: [master]
      event: tag

  docker-publish-16:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: rancher/cli
    context: package/
    tag:
    - latest
    - ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    build_args:
    - VERSION=${DRONE_TAG}
    when:
      branch: [v1.6]
      event: tag

  publish-release:
    image: plugins/gcs
    source: dist/artifacts/v*
    target: releases.rancher.com/cli
    acl:
      - allUsers:READER
    cache_control: public,max-age=3600
    secrets:
      - source: google_auth_key
        target: GOOGLE_CREDENTIALS
    when:
      branch: [master, v1.6]
      event: tag

  publish-latest:
    image: plugins/gcs
    source: dist/artifacts/latest/
    target: releases.rancher.com/cli/latest
    acl:
      - allUsers:READER
    cache_control: public,max-age=3600
    secrets:
      - source: google_auth_key
        target: GOOGLE_CREDENTIALS
    when:
      branch: v1.6
      event: tag
      ref:
        exclude: [ refs/tags/*rc* ]
