#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ -z "$GOOS" ]; then
    go build -ldflags "-X main.VERSION=$VERSION -linkmode external -extldflags -static" -o bin/rancher
else
    go build -ldflags "-X main.VERSION=$VERSION" -o bin/rancher
fi
