#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/cli .
docker build -t ${REPO}/cli:${TAG} .

echo Built ${REPO}/cli:${TAG}
