name: FOSSA

on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - v*
      - main

jobs:
  fossa:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # needed for the Vault authentication

    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/org/rancher/fossa/push token | FOSSA

      - name: Check FOSSA compliance
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1.9.0
        with:
          api-key: ${{ env.FOSSA }}
